# Generated by Django 4.1.3 on 2022-11-25 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aktor', '0001_initial'),
        ('film', '0004_alter_film_nazwa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('typ_roli', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('id_aktor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aktor.aktor')),
                ('id_film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='film.film')),
            ],
            options={
                'db_table': 'rola',
            },
        ),
    ]
