# Generated by Django 4.1.3 on 2022-11-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GatunekFilmu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatunek', models.CharField(blank=True, default=None, max_length=40, null=True)),
            ],
            options={
                'db_table': 'gatunekfilmu',
            },
        ),
    ]
