# Generated by Django 4.1.3 on 2022-11-23 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatunek_filmu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatunekfilmu',
            old_name='gatunek',
            new_name='gatunekk',
        ),
    ]
