# Generated by Django 4.1.3 on 2022-11-25 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menadzer', '0001_initial'),
        ('pracownik', '0002_alter_pracownik_data_urodzenia_and_more'),
        ('film', '0004_alter_film_nazwa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zadanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('opis', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('termin', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('id_film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_ffilmu', to='film.film', to_field='nazwa')),
                ('id_menadzer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_menadzera', to='menadzer.menadzer')),
                ('id_pracownik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_pracownika', to='pracownik.pracownik')),
            ],
            options={
                'db_table': 'zadanie',
            },
        ),
    ]
