# Generated by Django 4.1.3 on 2022-11-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('lat', models.FloatField(blank=True, default=None, null=True)),
                ('lon', models.FloatField(blank=True, default=None, null=True)),
                ('powierzchnia', models.CharField(blank=True, default=None, max_length=40, null=True)),
            ],
            options={
                'db_table': 'studio',
            },
        ),
    ]
