# Generated by Django 4.1.3 on 2022-11-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='nazwa',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, unique=True),
        ),
    ]
