# Generated by Django 4.1.3 on 2022-11-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownik',
            name='data_urodzenia',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='data_zatrudnienia',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='eemail',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
