# Generated by Django 4.1.3 on 2022-11-25 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gatunek_filmu', '0002_rename_gatunek_gatunekfilmu_gatunekk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('budzet', models.IntegerField(blank=True, default=None, null=True)),
                ('ograniczenie_wiekowe', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('data_premiery', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('id_gatunek', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gatunek_filmu.gatunekfilmu')),
            ],
            options={
                'db_table': 'film',
            },
        ),
    ]
