# Generated by Django 4.1.3 on 2022-11-25 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatunek_filmu', '0002_rename_gatunek_gatunekfilmu_gatunekk'),
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='id_gatunek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_gatunku', to='gatunek_filmu.gatunekfilmu'),
        ),
    ]
