# Generated by Django 4.1.3 on 2022-11-25 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatunek_filmu', '0003_alter_gatunekfilmu_gatunekk'),
        ('film', '0002_alter_film_id_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='id_gatunek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_gatunku', to='gatunek_filmu.gatunekfilmu', to_field='gatunekk'),
        ),
    ]
